version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: coworking-db
    environment:
      POSTGRES_DB: coworking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 9293709b13
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  coworking-app:
    build: .
    container_name: coworking-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/coworking
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 9293709b13
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: docker

volumes:
  postgres_data:
